services:
  - type: web
    name: chatfusion-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GENERATIVE_API_KEY
        sync: false
      - key: EMAIL
        sync: false
      - key: PASSWORD
        sync: false
      - key: AWS_BUCKET_NAME
        sync: false
      - key: AWS_ACCESS_KEY
        sync: false
      - key: AWS_SECRET
        sync: false
      - key: CLOUDINARY_ClOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
